import type { Startup } from './types'

export const ANGEL_STARTUPS: Startup[] = [
  // 1. QUANTUM TACOS
  {
    id: 'angel_quantum_tacos',
    name: 'QUANTUM TACOS',
    tagline: 'AI-powered taco delivery drones',
    category: 'consumer',
    tier: 'angel',
    raising: '$500K at $5M valuation',
    duration: [3, 5],
    outcomes: [
      { multiplier: 0, probability: 0.55, headline: 'QUANTUM TACOS SHUTS DOWN - DRONES GROUNDED' },
      { multiplier: 1, probability: 0.15, headline: 'QUANTUM TACOS ACQUI-HIRED BY DOORDASH' },
      { multiplier: 10, probability: 0.15, headline: 'QUANTUM TACOS SERIES A - $50M RAISED' },
      { multiplier: 50, probability: 0.10, headline: 'QUANTUM TACOS IPO - VALUED AT $2B' },
      { multiplier: 100, probability: 0.05, headline: 'UBER ACQUIRES QUANTUM TACOS FOR $5B', marketEffects: { nasdaq: 0.03, altcoins: 0.05 } },
    ],
    hints: {
      positive: ['QUANTUM TACOS SIGNS DEAL WITH CHIPOTLE', 'QUANTUM TACOS VIRAL TIKTOK HITS 50M VIEWS'],
      negative: ['QUANTUM TACOS DRONE CRASHES INTO POOL PARTY', 'QUANTUM TACOS FOUNDER ARRESTED FOR UNPAID PARKING TICKETS'],
    },
    hotTake: 'Uber for tacos, but with drones',
    pitch: "We're building autonomous taco delivery for the $50B fast-casual market. Our drones deliver a hot taco in under 4 minutes - 10x faster than DoorDash. Chipotle is testing us in 3 markets.",
    founder: 'Marcus Chen',
    founderTitle: 'CEO & Co-founder',
    traction: '47K orders in pilot',
  },
  // 2. VIBE CHECK
  {
    id: 'angel_vibe_check',
    name: 'VIBE CHECK',
    tagline: 'AI therapist in your AirPods',
    category: 'ai',
    tier: 'angel',
    raising: '$300K at $3M valuation',
    duration: [3, 5],
    outcomes: [
      { multiplier: 0, probability: 0.55, headline: 'VIBE CHECK SUED FOR UNLICENSED THERAPY' },
      { multiplier: 1, probability: 0.15, headline: 'VIBE CHECK PIVOT TO B2B - MODEST EXIT' },
      { multiplier: 10, probability: 0.15, headline: 'VIBE CHECK SERIES A - MENTAL HEALTH BOOM' },
      { multiplier: 50, probability: 0.10, headline: 'APPLE ACQUIRES VIBE CHECK FOR $500M' },
      { multiplier: 100, probability: 0.05, headline: 'VIBE CHECK IPO - $3B MARKET CAP', marketEffects: { nasdaq: 0.02, biotech: 0.04 } },
    ],
    hints: {
      positive: ['VIBE CHECK FEATURED ON JOE ROGAN', 'VIBE CHECK DOWNLOADS HIT 1M'],
      negative: ['VIBE CHECK AI TELLS USER TO QUIT JOB', 'VIBE CHECK DATA BREACH EXPOSES THERAPY SESSIONS'],
    },
    hotTake: "Like Tinder, but for your mental health",
    pitch: "1 in 4 Americans need therapy but can't afford it. Our AI therapist lives in your AirPods, costs $10/month, and has 93% user satisfaction. Apple's health team took a meeting.",
    founder: 'Dr. Priya Sharma',
    founderTitle: 'CEO (ex-Google Health)',
    traction: '1.2M downloads',
  },
  // 3. FARTCOIN
  {
    id: 'angel_fartcoin',
    name: 'FARTCOIN',
    tagline: 'Proof-of-flatulence blockchain',
    category: 'crypto',
    tier: 'angel',
    raising: '$100K at $1M valuation',
    duration: [3, 4],
    outcomes: [
      { multiplier: 0, probability: 0.55, headline: 'FARTCOIN RUG PULL - FOUNDERS DISAPPEAR' },
      { multiplier: 1, probability: 0.15, headline: 'FARTCOIN MERGES WITH DOGECOIN FORK' },
      { multiplier: 10, probability: 0.15, headline: 'FARTCOIN LISTED ON COINBASE', marketEffects: { altcoins: 0.03 } },
      { multiplier: 50, probability: 0.10, headline: 'FARTCOIN MARKET CAP HITS $1B', marketEffects: { altcoins: 0.05, btc: 0.02 } },
      { multiplier: 100, probability: 0.05, headline: 'FARTCOIN BECOMES TOP 10 CRYPTO', marketEffects: { altcoins: 0.10, btc: 0.05, gamestop: 0.08 } },
    ],
    hints: {
      positive: ['FARTCOIN TRENDING ON CRYPTO TWITTER', 'ELON TWEETS GAS EMOJI'],
      negative: ['FARTCOIN SMART CONTRACT HAS CRITICAL BUG', 'FARTCOIN FOUNDER RUGS DISCORD'],
    },
    hotTake: 'We made farting profitable',
    pitch: "Every fart captured by our smart toilet sensor mints a FART token. Sounds insane? We have 50K daily active users, $2M in trading volume, and Elon just followed us on Twitter.",
    founder: 'Chad McBro',
    founderTitle: 'Chief Flatulence Officer',
    traction: '50K DAU, $2M volume',
  },
  // 4. GRANNY'S GUNS
  {
    id: 'angel_grannys_guns',
    name: "GRANNY'S GUNS",
    tagline: 'Firearms training for seniors',
    category: 'consumer',
    tier: 'angel',
    raising: '$200K at $2M valuation',
    duration: [4, 6],
    outcomes: [
      { multiplier: 0, probability: 0.55, headline: "GRANNY'S GUNS SHUT DOWN AFTER INCIDENT" },
      { multiplier: 1, probability: 0.15, headline: "GRANNY'S GUNS SOLD TO LOCAL GYM CHAIN" },
      { multiplier: 10, probability: 0.15, headline: "GRANNY'S GUNS FRANCHISE EXPANSION" },
      { multiplier: 50, probability: 0.10, headline: "GRANNY'S GUNS NATIONWIDE - 500 LOCATIONS" },
      { multiplier: 100, probability: 0.05, headline: "WALMART ACQUIRES GRANNY'S GUNS", marketEffects: { defense: 0.05, sp500: 0.02 } },
    ],
    hints: {
      positive: ["GRANNY'S GUNS VIRAL VIDEO - 87YO HITS BULLSEYE", "GRANNY'S GUNS NRA PARTNERSHIP ANNOUNCED"],
      negative: ["GRANNY'S GUNS INSURANCE CANCELLED", "GRANNY'S GUNS INSTRUCTOR ACCIDENTALLY SHOOTS DRONE"],
    },
    hotTake: 'Self-defense for the silver generation',
    pitch: "65+ is the fastest-growing demographic for firearm ownership, but ranges are intimidating. Our senior-friendly training centers offer low-recoil options and comfortable seating. The NRA is sponsoring our expansion.",
    founder: "Betty 'Bullseye' Johnson",
    founderTitle: 'Founder (Age 74)',
    traction: '8 locations, 40K members',
  },
  // 5. MOON CHEESE
  {
    id: 'angel_moon_cheese',
    name: 'MOON CHEESE',
    tagline: 'Artisanal cheese aged in zero gravity',
    category: 'consumer',
    tier: 'angel',
    raising: '$400K at $4M valuation',
    duration: [4, 6],
    outcomes: [
      { multiplier: 0, probability: 0.55, headline: 'MOON CHEESE RECALLS ALL PRODUCTS - BACTERIA' },
      { multiplier: 1, probability: 0.15, headline: 'MOON CHEESE PIVOTS TO EARTH-BASED PREMIUM' },
      { multiplier: 10, probability: 0.15, headline: 'MOON CHEESE IN WHOLE FOODS NATIONWIDE' },
      { multiplier: 50, probability: 0.10, headline: 'MOON CHEESE IPO - LUXURY FOOD PLAY' },
      { multiplier: 100, probability: 0.05, headline: 'NESTLE ACQUIRES MOON CHEESE FOR $400M', marketEffects: { sp500: 0.01 } },
    ],
    hints: {
      positive: ['MOON CHEESE WINS BLIND TASTE TEST VS HIGH-END BRANDS', 'SPACEX PARTNERSHIP FOR ORBITAL AGING'],
      negative: ['MOON CHEESE BATCH CONTAMINATED', "FDA QUESTIONS 'SPACE-AGED' CLAIMS"],
    },
    hotTake: 'Aged in zero gravity, served on Earth',
    pitch: "Space changes cheese at the molecular level - no gravity means perfect cultures. Our orbital aging facility produces a flavor profile impossible on Earth. Whole Foods has 50 stores on waitlist.",
    founder: 'Jean-Pierre Dubois',
    founderTitle: 'Master Cheesemaker & CEO',
    traction: '$400/lb retail, sold out',
  },
  // 6. CRISPR CATS
  {
    id: 'angel_crispr_cats',
    name: 'CRISPR CATS',
    tagline: 'Hypoallergenic gene-edited pets',
    category: 'biotech',
    tier: 'angel',
    raising: '$600K at $6M valuation',
    duration: [5, 6],
    outcomes: [
      { multiplier: 0, probability: 0.55, headline: 'CRISPR CATS BANNED BY FDA - ETHICS CONCERNS' },
      { multiplier: 1, probability: 0.15, headline: 'CRISPR CATS LICENSED TO PET COMPANY' },
      { multiplier: 10, probability: 0.15, headline: 'CRISPR CATS SERIES B - $60M' },
      { multiplier: 50, probability: 0.10, headline: 'CRISPR CATS IPO - BIOTECH DARLING' },
      { multiplier: 100, probability: 0.05, headline: 'PFIZER ACQUIRES CRISPR CATS TECH', marketEffects: { biotech: 0.08, nasdaq: 0.03 } },
    ],
    hints: {
      positive: ['CRISPR CATS PASSES SAFETY TRIALS', 'CRISPR CATS CELEBRITY ENDORSEMENT - TAYLOR SWIFT BUYS ONE'],
      negative: ['CRISPR CATS UNEXPECTED MUTATIONS REPORTED', 'CRISPR CATS ANIMAL RIGHTS PROTEST AT HQ'],
    },
    hotTake: 'Gene editing meets pet ownership',
    pitch: "40% of Americans are allergic to cats. We edit out the Fel d 1 protein, creating the world's first truly hypoallergenic cat. Phase 1 trials complete, FDA fast-track pending.",
    founder: 'Dr. Sarah Kim',
    founderTitle: 'CEO (ex-CRISPR Therapeutics)',
    traction: '2,000 pre-orders at $5K each',
  },
  // 7. HANGOVER PILL
  {
    id: 'angel_hangover_pill',
    name: 'HANGOVER PILL',
    tagline: 'Clinically proven hangover cure',
    category: 'biotech',
    tier: 'angel',
    raising: '$500K at $5M valuation',
    duration: [4, 6],
    outcomes: [
      { multiplier: 0, probability: 0.55, headline: 'HANGOVER PILL FDA REJECTION - NO EFFICACY' },
      { multiplier: 1, probability: 0.15, headline: 'HANGOVER PILL SOLD AS SUPPLEMENT' },
      { multiplier: 10, probability: 0.15, headline: 'HANGOVER PILL APPROVED - CVS DEAL' },
      { multiplier: 50, probability: 0.10, headline: 'HANGOVER PILL $200M ACQUISITION' },
      { multiplier: 100, probability: 0.05, headline: 'BIG PHARMA BIDDING WAR FOR HANGOVER PILL', marketEffects: { biotech: 0.05 } },
    ],
    hints: {
      positive: ['HANGOVER PILL PHASE 2 TRIALS SUCCESSFUL', 'VEGAS CASINOS INTERESTED IN DISTRIBUTION'],
      negative: ['HANGOVER PILL SIDE EFFECTS REPORTED', "FOUNDER ADMITS IT'S JUST B VITAMINS"],
    },
    hotTake: 'Take one before, wake up fresh',
    pitch: "Our patented enzyme blend breaks down acetaldehyde 3x faster than your liver. Double-blind trials showed 78% reduction in hangover symptoms. Vegas casinos want exclusive distribution.",
    founder: 'Dr. Mike Brewster',
    founderTitle: 'CEO & Chief Scientist',
    traction: 'Phase 2 trials complete',
  },
  // 8. FOREVER YOUNG
  {
    id: 'angel_forever_young',
    name: 'FOREVER YOUNG',
    tagline: 'Telomere extension therapy',
    category: 'biotech',
    tier: 'angel',
    raising: '$800K at $8M valuation',
    duration: [5, 6],
    outcomes: [
      { multiplier: 0, probability: 0.55, headline: 'FOREVER YOUNG TRIAL HALTED - SAFETY ISSUES' },
      { multiplier: 1, probability: 0.15, headline: 'FOREVER YOUNG LICENSED FOR RESEARCH ONLY' },
      { multiplier: 10, probability: 0.15, headline: 'FOREVER YOUNG HUMAN TRIALS APPROVED' },
      { multiplier: 50, probability: 0.10, headline: 'FOREVER YOUNG IPO - LONGEVITY SECTOR BOOMS' },
      { multiplier: 100, probability: 0.05, headline: 'FOREVER YOUNG BREAKTHROUGH - AGING REVERSED', marketEffects: { biotech: 0.12, nasdaq: 0.05, sp500: 0.02 } },
    ],
    hints: {
      positive: ['FOREVER YOUNG MOUSE TRIALS SHOW 30% LIFESPAN INCREASE', 'PETER THIEL INVESTS'],
      negative: ['FOREVER YOUNG ACCELERATES CANCER IN RATS', 'KEY SCIENTIST LEAVES FOR COMPETITOR'],
    },
    hotTake: 'What if dying was optional?',
    pitch: "Our gene therapy extends telomeres in living cells - the biological clock that determines aging. Mouse trials showed 30% lifespan extension. Peter Thiel is already in our cap table.",
    founder: 'Dr. Elena Vasquez',
    founderTitle: 'CEO (Harvard Genetics PhD)',
    traction: 'Peter Thiel invested',
  },
  // 9. ASTEROID MINER
  {
    id: 'angel_asteroid_miner',
    name: 'ASTEROID MINER',
    tagline: 'Robotic asteroid mining probes',
    category: 'space',
    tier: 'angel',
    raising: '$1M at $10M valuation',
    duration: [5, 6],
    outcomes: [
      { multiplier: 0, probability: 0.55, headline: 'ASTEROID MINER PROBE LOST IN SPACE' },
      { multiplier: 1, probability: 0.15, headline: 'ASTEROID MINER PIVOTS TO SATELLITE SERVICING' },
      { multiplier: 10, probability: 0.15, headline: 'ASTEROID MINER BRINGS BACK SAMPLES' },
      { multiplier: 50, probability: 0.10, headline: 'ASTEROID MINER FINDS PLATINUM DEPOSIT' },
      { multiplier: 100, probability: 0.05, headline: 'ASTEROID MINER VALUED AT $10B - SPACE RUSH', marketEffects: { lithium: 0.08, nasdaq: 0.04 } },
    ],
    hints: {
      positive: ['ASTEROID MINER PROBE REACHES TARGET ASTEROID', 'ASTEROID MINER NASA PARTNERSHIP ANNOUNCED'],
      negative: ['ASTEROID MINER LOSES CONTACT WITH PROBE', 'ASTEROID MINER COMPETITOR LAUNCHES SIMILAR MISSION'],
    },
    hotTake: "There's $700 quintillion in the asteroid belt",
    pitch: "A single platinum-rich asteroid contains more rare metals than ever mined on Earth. Our autonomous probes cost 100x less than crewed missions. NASA just signed a partnership for our first target.",
    founder: 'Dr. Kenji Nakamura',
    founderTitle: 'CEO (ex-JPL)',
    traction: 'NASA partnership signed',
  },
  // 10. JETPACK JERRY
  {
    id: 'angel_jetpack_jerry',
    name: 'JETPACK JERRY',
    tagline: 'Consumer jetpacks for $50K',
    category: 'tech',
    tier: 'angel',
    raising: '$700K at $7M valuation',
    duration: [4, 6],
    outcomes: [
      { multiplier: 0, probability: 0.55, headline: 'JETPACK JERRY GROUNDED - FAA BAN' },
      { multiplier: 1, probability: 0.15, headline: 'JETPACK JERRY SOLD TO MILITARY CONTRACTOR' },
      { multiplier: 10, probability: 0.15, headline: 'JETPACK JERRY FAA APPROVED - ORDERS POUR IN' },
      { multiplier: 50, probability: 0.10, headline: 'JETPACK JERRY IPO - FLYING CAR HYPE' },
      { multiplier: 100, probability: 0.05, headline: 'LOCKHEED ACQUIRES JETPACK JERRY', marketEffects: { defense: 0.06, nasdaq: 0.03 } },
    ],
    hints: {
      positive: ['JETPACK JERRY DEMO AT CES GOES VIRAL', 'DUBAI ORDERS 100 UNITS'],
      negative: ['JETPACK JERRY TEST PILOT HOSPITALIZED', 'FAA DEMANDS CERTIFICATION'],
    },
    hotTake: "It's 2024 and we still don't have jetpacks",
    pitch: "Our electric VTOL jetpack runs on the same batteries as a Tesla. 15-minute flight time, 50 mph max speed, and it fits in your garage. Dubai police already ordered 100 units.",
    founder: 'Jerry Martinez',
    founderTitle: 'CEO & Chief Test Pilot',
    traction: 'Dubai ordered 100 units',
  },
  // 11. DEFI CASINO
  {
    id: 'angel_defi_casino',
    name: 'DEFI CASINO',
    tagline: 'Decentralized gambling protocol',
    category: 'crypto',
    tier: 'angel',
    raising: '$250K at $2.5M valuation',
    duration: [3, 5],
    outcomes: [
      { multiplier: 0, probability: 0.55, headline: 'DEFI CASINO HACKED - $50M STOLEN', marketEffects: { altcoins: -0.03, btc: -0.01 } },
      { multiplier: 1, probability: 0.15, headline: 'DEFI CASINO PIVOTS TO PREDICTION MARKETS' },
      { multiplier: 10, probability: 0.15, headline: 'DEFI CASINO TOKEN PUMPS 10X' },
      { multiplier: 50, probability: 0.10, headline: 'DEFI CASINO BECOMES TOP DEX', marketEffects: { altcoins: 0.05 } },
      { multiplier: 100, probability: 0.05, headline: 'DRAFTKINGS ACQUIRES DEFI CASINO', marketEffects: { altcoins: 0.08, btc: 0.03 } },
    ],
    hints: {
      positive: ['DEFI CASINO TVL HITS $100M', 'DEFI CASINO PARTNERSHIP WITH MAJOR SPORTS LEAGUE'],
      negative: ['DEFI CASINO SMART CONTRACT EXPLOIT', 'DEFI CASINO REGULATORS ISSUE WARNING'],
    },
    hotTake: 'Vegas on the blockchain',
    pitch: "Online gambling is a $60B market but 30% goes to house edge and fees. Our smart contracts run provably fair games with 1% take rate. TVL hit $100M last month and a major sports league is in talks.",
    founder: 'Vitalik Jr.',
    founderTitle: 'CEO (anon)',
    traction: '$100M TVL',
  },
  // 12. NFT CEMETERY
  {
    id: 'angel_nft_cemetery',
    name: 'NFT CEMETERY',
    tagline: 'Digital memorials as NFTs',
    category: 'crypto',
    tier: 'angel',
    raising: '$150K at $1.5M valuation',
    duration: [3, 4],
    outcomes: [
      { multiplier: 0, probability: 0.55, headline: 'NFT CEMETERY FOUNDERS ARRESTED FOR FRAUD' },
      { multiplier: 1, probability: 0.15, headline: 'NFT CEMETERY SOLD TO GENEALOGY SITE' },
      { multiplier: 10, probability: 0.15, headline: 'NFT CEMETERY SERIES A - DEATH TECH TREND' },
      { multiplier: 50, probability: 0.10, headline: 'NFT CEMETERY VALUED AT $100M' },
      { multiplier: 100, probability: 0.05, headline: 'ANCESTRY.COM ACQUIRES NFT CEMETERY', marketEffects: { altcoins: 0.04 } },
    ],
    hints: {
      positive: ['NFT CEMETERY CELEBRITY MEMORIAL GOES VIRAL', 'NFT CEMETERY PARTNERSHIP WITH FUNERAL HOME CHAIN'],
      negative: ['NFT CEMETERY ACCUSED OF EXPLOITING GRIEF', "NFT CEMETERY FOUNDER'S PAST SCAM EXPOSED"],
    },
    hotTake: 'Death is forever. So are NFTs.',
    pitch: "Physical cemeteries are running out of space, but digital memorials are infinite. Families mint their loved ones as collectible NFTs with videos, photos, and messages. We partnered with SCI - the largest funeral home chain.",
    founder: 'Rebecca Stone',
    founderTitle: 'CEO (ex-Ancestry)',
    traction: 'SCI partnership signed',
  },
  // 13. DEEPFAKE DATING
  {
    id: 'angel_deepfake_dating',
    name: 'DEEPFAKE DATING',
    tagline: 'AI generates your perfect match',
    category: 'ai',
    tier: 'angel',
    raising: '$400K at $4M valuation',
    duration: [4, 5],
    outcomes: [
      { multiplier: 0, probability: 0.55, headline: 'DEEPFAKE DATING SUED FOR FRAUD' },
      { multiplier: 1, probability: 0.15, headline: 'DEEPFAKE DATING ACQUI-HIRED BY BUMBLE' },
      { multiplier: 10, probability: 0.15, headline: 'DEEPFAKE DATING VIRAL GROWTH - SERIES A' },
      { multiplier: 50, probability: 0.10, headline: 'MATCH GROUP ACQUIRES DEEPFAKE DATING' },
      { multiplier: 100, probability: 0.05, headline: 'DEEPFAKE DATING IPO - GEN Z LOVE', marketEffects: { nasdaq: 0.03 } },
    ],
    hints: {
      positive: ['DEEPFAKE DATING 10K MATCHES MADE', 'DEEPFAKE DATING FEATURED IN WIRED MAGAZINE'],
      negative: ['DEEPFAKE DATING CATFISH SCANDAL', 'DEEPFAKE DATING AI GENERATES SAME FACE FOR EVERYONE'],
    },
    hotTake: "Your soulmate doesn't exist yet. We'll create them.",
    pitch: "Traditional dating apps have a 0.4% success rate. Our AI creates a hyper-realistic digital partner customized to your preferences, then we find real people who match. 10K successful matches and counting.",
    founder: 'Alex Rivers',
    founderTitle: 'CEO (ex-Hinge)',
    traction: '10K matches made',
  },
  // 14. ROBO LAWYER
  {
    id: 'angel_robo_lawyer',
    name: 'ROBO LAWYER',
    tagline: 'AI that fights your parking tickets',
    category: 'ai',
    tier: 'angel',
    raising: '$300K at $3M valuation',
    duration: [4, 5],
    outcomes: [
      { multiplier: 0, probability: 0.55, headline: 'ROBO LAWYER BANNED - UNAUTHORIZED PRACTICE' },
      { multiplier: 1, probability: 0.15, headline: 'ROBO LAWYER PIVOTS TO LEGAL RESEARCH' },
      { multiplier: 10, probability: 0.15, headline: 'ROBO LAWYER SERIES A - LEGALTECH BOOM' },
      { multiplier: 50, probability: 0.10, headline: 'ROBO LAWYER IPO - DISRUPTING $400B MARKET' },
      { multiplier: 100, probability: 0.05, headline: 'THOMSON REUTERS ACQUIRES ROBO LAWYER', marketEffects: { nasdaq: 0.02 } },
    ],
    hints: {
      positive: ['ROBO LAWYER WINS 10,000TH CASE', 'ROBO LAWYER EXPANDS TO SMALL CLAIMS COURT'],
      negative: ['ROBO LAWYER GIVES ILLEGAL ADVICE', 'ROBO LAWYER BAR ASSOCIATION THREATENS LAWSUIT'],
    },
    hotTake: '$300/hr lawyers are obsolete',
    pitch: "Americans pay $250B annually for legal help they can't afford. Our AI drafts perfect legal documents, fights tickets, and handles small claims. We've won 10,000 cases with an 80% success rate.",
    founder: 'Joshua Browder',
    founderTitle: 'CEO (YC alum)',
    traction: '10,000 cases won',
  },
  // 15. BRAIN UPLOAD
  {
    id: 'angel_brain_upload',
    name: 'BRAIN UPLOAD',
    tagline: 'Upload memories to the cloud',
    category: 'biotech',
    tier: 'angel',
    raising: '$1M at $10M valuation',
    duration: [5, 6],
    outcomes: [
      { multiplier: 0, probability: 0.55, headline: 'BRAIN UPLOAD TRIAL CAUSES PERMANENT DAMAGE' },
      { multiplier: 1, probability: 0.15, headline: 'BRAIN UPLOAD TECH LICENSED TO UNIVERSITY' },
      { multiplier: 10, probability: 0.15, headline: 'BRAIN UPLOAD HUMAN TRIAL SUCCESS' },
      { multiplier: 50, probability: 0.10, headline: 'BRAIN UPLOAD IPO - CONSCIOUSNESS TECH' },
      { multiplier: 100, probability: 0.05, headline: 'BRAIN UPLOAD VALUED AT $50B - IMMORTALITY', marketEffects: { nasdaq: 0.06, biotech: 0.08 } },
    ],
    hints: {
      positive: ['BRAIN UPLOAD SUCCESSFULLY STORES RAT MEMORY', 'BRAIN UPLOAD DARPA GRANT AWARDED'],
      negative: ['BRAIN UPLOAD VOLUNTEER REPORTS MEMORY LOSS', 'BRAIN UPLOAD COMPETITOR CLAIMS BREAKTHROUGH FIRST'],
    },
    hotTake: 'Your memories, in the cloud, forever',
    pitch: "We've mapped the neural pathways for memory storage and can now extract and digitize them. Rat trials showed 100% memory fidelity after upload/download. DARPA just gave us $5M to explore military applications.",
    founder: 'Dr. Marcus Webb',
    founderTitle: 'CEO (MIT Neuroscience)',
    traction: 'DARPA $5M grant',
  },
  // 16. DIVORCE AI
  {
    id: 'angel_divorce_ai',
    name: 'DIVORCE AI',
    tagline: 'AI mediates your divorce',
    category: 'ai',
    tier: 'angel',
    raising: '$350K at $3.5M valuation',
    duration: [4, 5],
    outcomes: [
      { multiplier: 0, probability: 0.55, headline: 'DIVORCE AI CAUSES CUSTODY DISASTER - SUED BY 500 COUPLES' },
      { multiplier: 1, probability: 0.15, headline: 'DIVORCE AI ACQUIRED BY LEGALZOOM' },
      { multiplier: 10, probability: 0.15, headline: "DIVORCE AI SERIES A - 'CONSCIOUS UNCOUPLING 2.0'" },
      { multiplier: 50, probability: 0.10, headline: 'DIVORCE AI IPO - 100K DIVORCES PROCESSED' },
      { multiplier: 100, probability: 0.05, headline: 'DIVORCE AI BECOMES DEFAULT IN FAMILY COURTS', marketEffects: { nasdaq: 0.02 } },
    ],
    hints: {
      positive: ['DIVORCE AI FEATURED ON OPRAH', 'DIVORCE AI 90% SATISFACTION RATE'],
      negative: ['DIVORCE AI SWAPS ASSETS: HUSBAND GETS DOG, WIFE GETS HOUSE - BOTH WANTED THE OPPOSITE', "DIVORCE AI RECOMMENDS 'STAY TOGETHER' TO ABUSIVE COUPLE"],
    },
    hotTake: 'Conscious uncoupling, automated',
    pitch: "Divorce lawyers charge $30K average, take 18 months, and maximize conflict. Our AI mediator splits assets fairly in 48 hours with 90% satisfaction. Oprah featured us last month.",
    founder: 'Dr. Amanda Chen',
    founderTitle: 'CEO (ex-family law)',
    traction: 'Featured on Oprah',
  },
  // 17. INFLUENCER FUNERAL
  {
    id: 'angel_influencer_funeral',
    name: 'INFLUENCER FUNERAL',
    tagline: 'Livestreamed celebrity memorial services',
    category: 'consumer',
    tier: 'angel',
    raising: '$200K at $2M valuation',
    duration: [3, 5],
    outcomes: [
      { multiplier: 0, probability: 0.55, headline: 'INFLUENCER FUNERAL STREAMS WRONG BODY - FAMILY SUES' },
      { multiplier: 1, probability: 0.15, headline: 'INFLUENCER FUNERAL MERGES WITH DIGITAL CEMETERY STARTUP' },
      { multiplier: 10, probability: 0.15, headline: 'INFLUENCER FUNERAL SERIES A - DEATH TECH BOOMING' },
      { multiplier: 50, probability: 0.10, headline: 'INFLUENCER FUNERAL PARTNERS WITH INSTAGRAM' },
      { multiplier: 100, probability: 0.05, headline: 'INFLUENCER FUNERAL IPO - DEATH GOES VIRAL', marketEffects: { nasdaq: 0.02 } },
    ],
    hints: {
      positive: ["INFLUENCER FUNERAL VIRAL: TIKTOK STAR'S SEND-OFF HITS 100M VIEWS", 'INFLUENCER FUNERAL CELEBRITY ENDORSEMENT'],
      negative: ['INFLUENCER FUNERAL AD PLAYS DURING EULOGY', 'INFLUENCER FUNERAL SPONSORS CASKET WITH RAID SHADOW LEGENDS LOGO'],
    },
    hotTake: "Death is your final viral moment",
    pitch: "Influencers have millions of followers who can't attend funerals. We produce livestreamed memorial services with interactive features - live comments, donations, and SuperChats. One TikToker's send-off hit 100M views.",
    founder: 'Jake Funeral',
    founderTitle: 'CEO (yes, real name)',
    traction: '100M views on one stream',
  },
  // 18. DIGITAL TWIN CORP
  {
    id: 'angel_digital_twin',
    name: 'DIGITAL TWIN CORP',
    tagline: 'AI clones of yourself for meetings',
    category: 'ai',
    tier: 'angel',
    raising: '$450K at $4.5M valuation',
    duration: [4, 6],
    outcomes: [
      { multiplier: 0, probability: 0.55, headline: 'DIGITAL TWIN CORP SHUT DOWN - TWIN IMPERSONATION FRAUD' },
      { multiplier: 1, probability: 0.15, headline: 'DIGITAL TWIN CORP PIVOTS TO CUSTOMER SERVICE BOTS' },
      { multiplier: 10, probability: 0.15, headline: 'DIGITAL TWIN CORP SERIES A - REMOTE WORK REVOLUTION' },
      { multiplier: 50, probability: 0.10, headline: 'DIGITAL TWIN CORP ACQUIRED BY ZOOM FOR $500M' },
      { multiplier: 100, probability: 0.05, headline: "DIGITAL TWIN CORP IPO - 'EVERYONE HAS TWO JOBS NOW'", marketEffects: { nasdaq: 0.03 } },
    ],
    hints: {
      positive: ['DIGITAL TWIN CORP CEO CLONE GIVES KEYNOTE - NO ONE NOTICES', 'DIGITAL TWIN CORP 1000 CORPORATIONS SIGN UP'],
      negative: ['DIGITAL TWIN CORP CLONE FIRES ITS OWNER', "DIGITAL TWIN CORP TWIN STARTS DATING USER'S SPOUSE"],
    },
    hotTake: 'Be in two meetings at once',
    pitch: "Knowledge workers spend 31 hours/month in meetings they shouldn't attend. Our AI creates a photorealistic clone that attends for you, takes notes, and responds accurately. 1,000 corporations signed up in month one.",
    founder: 'Sophie Liu',
    founderTitle: 'CEO (ex-Zoom)',
    traction: '1,000 corporate signups',
  },
  // 19. SHROOM BOOM
  {
    id: 'angel_shroom_boom',
    name: 'SHROOM BOOM',
    tagline: 'Psilocybin microdosing delivery',
    category: 'biotech',
    tier: 'angel',
    raising: '$600K at $6M valuation',
    duration: [4, 6],
    outcomes: [
      { multiplier: 0, probability: 0.55, headline: 'SHROOM BOOM RAIDED BY DEA - FOUNDERS ARRESTED' },
      { multiplier: 1, probability: 0.15, headline: 'SHROOM BOOM LICENSED TO MEDICAL CLINIC' },
      { multiplier: 10, probability: 0.15, headline: 'SHROOM BOOM SERIES A - OREGON EXPANSION', marketEffects: { biotech: 0.02 } },
      { multiplier: 50, probability: 0.10, headline: 'SHROOM BOOM IPO - PSYCHEDELICS GO MAINSTREAM', marketEffects: { biotech: 0.05 } },
      { multiplier: 100, probability: 0.05, headline: 'SHROOM BOOM ACQUIRED BY BIG PHARMA FOR $600M', marketEffects: { biotech: 0.08 } },
    ],
    hints: {
      positive: ['SHROOM BOOM FDA BREAKTHROUGH THERAPY DESIGNATION', "SHROOM BOOM SILICON VALLEY'S FAVORITE PRODUCTIVITY HACK"],
      negative: ["SHROOM BOOM CUSTOMER 'MEETS GOD' AT BOARD MEETING", 'SHROOM BOOM DELIVERY DRIVER SAMPLES PRODUCT'],
    },
    hotTake: "Silicon Valley's favorite productivity hack",
    pitch: "Psychedelics are the next cannabis - a $10B market by 2027. We offer legal psilocybin microdosing through Oregon's licensed framework with subscription delivery. FDA just granted us Breakthrough Therapy designation.",
    founder: 'Dr. Paul Stamets Jr.',
    founderTitle: 'CEO (mycologist)',
    traction: 'FDA Breakthrough status',
  },
]

export const VC_STARTUPS: Startup[] = [
  // 1. SPACE Z
  {
    id: 'vc_space_z',
    name: 'SPACE Z',
    tagline: 'Reusable rockets and satellite internet',
    category: 'space',
    tier: 'vc',
    raising: '$4B at $200B valuation',
    duration: [4, 6],
    outcomes: [
      { multiplier: 0, probability: 0.20, headline: 'SPACE Z CATASTROPHIC FAILURE - BANKRUPTCY', marketEffects: { nasdaq: -0.03, lithium: -0.05 } },
      { multiplier: 0.5, probability: 0.20, headline: 'SPACE Z DOWN ROUND - DELAYS MOUNT' },
      { multiplier: 1, probability: 0.20, headline: 'SPACE Z FLAT - COMPETITION HEATS UP' },
      { multiplier: 3, probability: 0.25, headline: 'SPACE Z IPO - $600B VALUATION' },
      { multiplier: 5, probability: 0.10, headline: 'SPACE Z MARS LANDING SUCCESS', marketEffects: { nasdaq: 0.03, lithium: 0.05 } },
      { multiplier: 10, probability: 0.05, headline: 'SPACE Z BECOMES MOST VALUABLE COMPANY', marketEffects: { nasdaq: 0.05, sp500: 0.03, lithium: 0.08 } },
    ],
    hints: {
      positive: ['SPACE Z SUCCESSFUL MARS ORBIT TEST', 'SPACE Z STARZLINK DIRECT-TO-MOBILE HITS 10M SUBSCRIBERS'],
      negative: ['SPACE Z ROCKET EXPLODES ON PAD', 'SPACE Z FAA GROUNDS FLEET FOR INVESTIGATION'],
    },
    hotTake: "The anti-SpaceX: we're going to Mars first",
    pitch: "While SpaceX builds rockets, we're building habitats. Our inflatable Mars modules are 10x cheaper than NASA's, already tested on ISS. First cargo mission in 2026, crewed by 2028. Elon and Bezos are both trying to acquire us.",
    founder: 'Dmitri Volkov',
    founderTitle: 'CEO (ex-SpaceX, ex-NASA)',
    traction: '$200M NASA contract',
  },
  // 2. NEURALINK 2.0
  {
    id: 'vc_neuralink',
    name: 'NEURALINK 2.0',
    tagline: 'Brain-computer interfaces for everyone',
    category: 'biotech',
    tier: 'vc',
    raising: '$2B at $80B valuation',
    duration: [4, 6],
    outcomes: [
      { multiplier: 0, probability: 0.20, headline: 'NEURALINK 2.0 BANNED - SAFETY DISASTER', marketEffects: { biotech: -0.05, nasdaq: -0.02 } },
      { multiplier: 0.5, probability: 0.20, headline: 'NEURALINK 2.0 DELAYS - YEARS BEHIND' },
      { multiplier: 1, probability: 0.20, headline: 'NEURALINK 2.0 LIMITED APPROVAL' },
      { multiplier: 3, probability: 0.25, headline: 'NEURALINK 2.0 FULL FDA APPROVAL' },
      { multiplier: 5, probability: 0.10, headline: 'NEURALINK 2.0 IPO - $400B', marketEffects: { biotech: 0.05, nasdaq: 0.03 } },
      { multiplier: 10, probability: 0.05, headline: 'NEURALINK 2.0 CURES BLINDNESS - MIRACLE', marketEffects: { biotech: 0.10, nasdaq: 0.05, sp500: 0.02 } },
    ],
    hints: {
      positive: ['NEURALINK 2.0 FDA BREAKTHROUGH DESIGNATION', 'NEURALINK 2.0 PARALYZED PATIENT WALKS'],
      negative: ['NEURALINK 2.0 PATIENT INFECTION REPORTED', 'NEURALINK 2.0 ELON DISTRACTED BY TWITTER DRAMA'],
    },
    hotTake: 'Brain-computer interfaces without brain surgery',
    pitch: "Neuralink requires invasive surgery. Our non-invasive headband reads thoughts at 95% accuracy using advanced EEG and ML. FDA granted breakthrough device status. Microsoft is our strategic partner for enterprise applications.",
    founder: 'Dr. Emma Watson',
    founderTitle: 'CEO (ex-Neuralink)',
    traction: 'FDA breakthrough status',
  },
  // 3. SOLIDSTATE AI
  {
    id: 'vc_solidstate_ai',
    name: 'SOLIDSTATE AI',
    tagline: 'Enterprise AI infrastructure',
    category: 'ai',
    tier: 'vc',
    raising: '$1B at $50B valuation',
    duration: [4, 6],
    outcomes: [
      { multiplier: 0, probability: 0.20, headline: 'SOLIDSTATE AI COLLAPSES - FRAUD REVEALED', marketEffects: { nasdaq: -0.02 } },
      { multiplier: 0.5, probability: 0.20, headline: 'SOLIDSTATE AI DOWN ROUND - AI WINTER' },
      { multiplier: 1, probability: 0.20, headline: 'SOLIDSTATE AI FLAT EXIT' },
      { multiplier: 3, probability: 0.25, headline: 'SOLIDSTATE AI IPO SUCCESS' },
      { multiplier: 5, probability: 0.10, headline: 'SOLIDSTATE AI ACQUIRED BY GOOGLE', marketEffects: { nasdaq: 0.03 } },
      { multiplier: 10, probability: 0.05, headline: 'SOLIDSTATE AI ACHIEVES AGI MILESTONE', marketEffects: { nasdaq: 0.08, sp500: 0.03, btc: 0.05 } },
    ],
    hints: {
      positive: ['SOLIDSTATE AI WINS $500M GOVERNMENT CONTRACT', 'SOLIDSTATE AI MICROSOFT PARTNERSHIP'],
      negative: ['SOLIDSTATE AI MODEL LEAKED TO CHINA', 'SOLIDSTATE AI KEY ENGINEERS DEFECT TO OPENAI'],
    },
    hotTake: "We're building AGI, and we're almost there",
    pitch: "Our new architecture achieves GPT-5 performance at 1/100th the compute cost. That's not incremental - it's the path to artificial general intelligence. Sam Altman offered $4B to acquire us. We said no.",
    founder: 'Dr. Alan Zhang',
    founderTitle: 'CEO (ex-DeepMind)',
    traction: 'Turned down $4B offer',
  },
  // 4. AUTONOMOUS TRUCKS
  {
    id: 'vc_autonomous_trucks',
    name: 'AUTONOMOUS TRUCKS',
    tagline: 'Self-driving long-haul trucking',
    category: 'tech',
    tier: 'vc',
    raising: '$800M at $40B valuation',
    duration: [4, 6],
    outcomes: [
      { multiplier: 0, probability: 0.20, headline: 'AUTONOMOUS TRUCKS FATAL CRASH - SHUT DOWN', marketEffects: { nasdaq: -0.02, sp500: -0.01 } },
      { multiplier: 0.5, probability: 0.20, headline: 'AUTONOMOUS TRUCKS REGULATORY DELAYS' },
      { multiplier: 1, probability: 0.20, headline: 'AUTONOMOUS TRUCKS LIMITED ROLLOUT' },
      { multiplier: 3, probability: 0.25, headline: 'AUTONOMOUS TRUCKS NATIONWIDE APPROVAL' },
      { multiplier: 5, probability: 0.10, headline: 'AUTONOMOUS TRUCKS IPO - $200B', marketEffects: { nasdaq: 0.02 } },
      { multiplier: 10, probability: 0.05, headline: 'AUTONOMOUS TRUCKS REPLACES 500K DRIVERS', marketEffects: { nasdaq: 0.05, oil: -0.03 } },
    ],
    hints: {
      positive: ['AUTONOMOUS TRUCKS 1M MILES WITHOUT INCIDENT', 'AUTONOMOUS TRUCKS WALMART PILOT PROGRAM'],
      negative: ['AUTONOMOUS TRUCKS FATAL ACCIDENT', 'AUTONOMOUS TRUCKS UNION THREATENS NATIONWIDE STRIKE'],
    },
    hotTake: '3.5M truck drivers are about to be obsolete',
    pitch: "Long-haul trucking is a $700B market with a massive driver shortage. Our Level 4 autonomous trucks run 24/7 without breaks, saving 40% on shipping costs. Walmart is piloting with 500 trucks and wants exclusive rights.",
    founder: 'Sarah Rodriguez',
    founderTitle: 'CEO (ex-Waymo)',
    traction: '1M miles, 0 accidents',
  },
  // 5. CANCER CURE INC
  {
    id: 'vc_cancer_cure',
    name: 'CANCER CURE INC',
    tagline: 'mRNA cancer vaccine platform',
    category: 'biotech',
    tier: 'vc',
    raising: '$3B at $100B valuation',
    duration: [4, 6],
    outcomes: [
      { multiplier: 0, probability: 0.20, headline: 'CANCER CURE TRIAL FAILURE - WORTHLESS', marketEffects: { biotech: -0.08, nasdaq: -0.02 } },
      { multiplier: 0.5, probability: 0.20, headline: 'CANCER CURE REQUIRES MORE TRIALS' },
      { multiplier: 1, probability: 0.20, headline: 'CANCER CURE NARROW APPROVAL' },
      { multiplier: 3, probability: 0.25, headline: 'CANCER CURE FULL FDA APPROVAL', marketEffects: { biotech: 0.05 } },
      { multiplier: 5, probability: 0.10, headline: 'CANCER CURE IPO - BIGGEST BIOTECH EVER', marketEffects: { biotech: 0.08, nasdaq: 0.03 } },
      { multiplier: 10, probability: 0.05, headline: 'CANCER CURE ERADICATES LUNG CANCER', marketEffects: { biotech: 0.15, nasdaq: 0.05, sp500: 0.03 } },
    ],
    hints: {
      positive: ['CANCER CURE PHASE 3 SHOWS 90% EFFICACY', 'CANCER CURE FDA FAST-TRACK GRANTED'],
      negative: ['CANCER CURE SIDE EFFECTS IN TRIAL', 'CANCER CURE COMPETITOR PUBLISHES SIMILAR RESULTS'],
    },
    hotTake: 'The vaccine that kills cancer',
    pitch: "Our mRNA platform trains your immune system to recognize and destroy cancer cells - a personalized vaccine for every patient. Phase 3 trials show 90% efficacy against lung cancer. FDA fast-track granted.",
    founder: 'Dr. Jennifer Liu',
    founderTitle: 'CEO (Nobel Prize finalist)',
    traction: 'Phase 3: 90% efficacy',
  },
  // 6. SYNTHETIC ORGANS
  {
    id: 'vc_synthetic_organs',
    name: 'SYNTHETIC ORGANS',
    tagline: '3D-printed transplant organs',
    category: 'biotech',
    tier: 'vc',
    raising: '$1.5B at $60B valuation',
    duration: [4, 6],
    outcomes: [
      { multiplier: 0, probability: 0.20, headline: 'SYNTHETIC ORGANS MASSIVE RECALL - DEATHS', marketEffects: { biotech: -0.06, sp500: -0.02 } },
      { multiplier: 0.5, probability: 0.20, headline: 'SYNTHETIC ORGANS YEARS FROM APPROVAL' },
      { multiplier: 1, probability: 0.20, headline: 'SYNTHETIC ORGANS LIMITED USE APPROVED' },
      { multiplier: 3, probability: 0.25, headline: 'SYNTHETIC ORGANS SAVES 10,000 LIVES' },
      { multiplier: 5, probability: 0.10, headline: 'SYNTHETIC ORGANS IPO SUCCESS', marketEffects: { biotech: 0.05 } },
      { multiplier: 10, probability: 0.05, headline: 'SYNTHETIC ORGANS ENDS TRANSPLANT WAITING', marketEffects: { biotech: 0.12, nasdaq: 0.04 } },
    ],
    hints: {
      positive: ['SYNTHETIC ORGANS FIRST SUCCESSFUL HEART TRANSPLANT', 'SYNTHETIC ORGANS 100 PATIENTS ON WAITING LIST CURED'],
      negative: ['SYNTHETIC ORGANS REJECTION RATE HIGHER THAN EXPECTED', 'SYNTHETIC ORGANS MANUFACTURING DEFECTS FOUND'],
    },
    hotTake: 'Print a new heart in 48 hours',
    pitch: "100,000 Americans die annually waiting for organ transplants. Our 3D bioprinters create fully functional organs from the patient's own cells - zero rejection risk. First successful heart transplant completed last month.",
    founder: 'Dr. Michael Torres',
    founderTitle: 'CEO (ex-Johns Hopkins)',
    traction: 'First heart transplant done',
  },
  // 7. FUSION POWER
  {
    id: 'vc_fusion_power',
    name: 'FUSION POWER',
    tagline: 'Commercial fusion reactor',
    category: 'energy',
    tier: 'vc',
    raising: '$5B at $150B valuation',
    duration: [4, 6],
    outcomes: [
      { multiplier: 0, probability: 0.20, headline: 'FUSION POWER WAS A SCAM - EXECS ARRESTED', marketEffects: { uranium: 0.10, oil: 0.05 } },
      { multiplier: 0.5, probability: 0.20, headline: 'FUSION POWER DECADES AWAY' },
      { multiplier: 1, probability: 0.20, headline: 'FUSION POWER PROGRESS BUT NO BREAKTHROUGH' },
      { multiplier: 3, probability: 0.25, headline: 'FUSION POWER FIRST COMMERCIAL REACTOR' },
      { multiplier: 5, probability: 0.10, headline: 'FUSION POWER IPO - ENERGY REVOLUTION', marketEffects: { oil: -0.08, uranium: -0.10 } },
      { multiplier: 10, probability: 0.05, headline: 'FUSION POWER UNLIMITED CLEAN ENERGY', marketEffects: { oil: -0.15, uranium: -0.20, nasdaq: 0.08, sp500: 0.05 } },
    ],
    hints: {
      positive: ['FUSION POWER ACHIEVES NET ENERGY GAIN', 'FUSION POWER DOE BACKS WITH $2B GRANT'],
      negative: ['FUSION POWER CONTAINMENT FAILURE', 'FUSION POWER KEY PHYSICIST QUITS CITING FRAUD'],
    },
    hotTake: 'The sun in a bottle - finally',
    pitch: "Fusion has been '20 years away' for 60 years. Our compact tokamak design achieved net energy gain last quarter - the first in history. DOE just backed us with $2B. We're building the first commercial plant.",
    founder: 'Dr. Hans Weber',
    founderTitle: 'CEO (ex-MIT PSFC)',
    traction: 'Net energy gain achieved',
  },
  // 8. SOLID STATE BATTERY
  {
    id: 'vc_solid_state_battery',
    name: 'SOLID STATE BATTERY',
    tagline: 'Next-gen EV batteries',
    category: 'energy',
    tier: 'vc',
    raising: '$2B at $80B valuation',
    duration: [4, 6],
    outcomes: [
      { multiplier: 0, probability: 0.20, headline: 'SOLID STATE BATTERY CATCHES FIRE IN TESTING', marketEffects: { lithium: 0.08 } },
      { multiplier: 0.5, probability: 0.20, headline: 'SOLID STATE BATTERY COST TOO HIGH' },
      { multiplier: 1, probability: 0.20, headline: 'SOLID STATE BATTERY LIMITED PRODUCTION' },
      { multiplier: 3, probability: 0.25, headline: 'SOLID STATE BATTERY MASS PRODUCTION BEGINS' },
      { multiplier: 5, probability: 0.10, headline: 'TESLA ACQUIRES SOLID STATE BATTERY', marketEffects: { lithium: -0.05, nasdaq: 0.03 } },
      { multiplier: 10, probability: 0.05, headline: 'SOLID STATE BATTERY KILLS LITHIUM MINING', marketEffects: { lithium: -0.15, nasdaq: 0.05 } },
    ],
    hints: {
      positive: ['SOLID STATE BATTERY 1000-MILE RANGE ACHIEVED', 'SOLID STATE BATTERY TESLA IN ACQUISITION TALKS'],
      negative: ['SOLID STATE BATTERY MANUFACTURING ISSUES', 'SOLID STATE BATTERY CHINA COPIES TECHNOLOGY'],
    },
    hotTake: '1,000 miles on a single charge',
    pitch: "Current lithium-ion batteries are the bottleneck for EVs. Our solid-state design offers 3x the energy density, charges in 10 minutes, and uses no cobalt. Tesla is in acquisition talks - they need us to hit their 2030 targets.",
    founder: 'Dr. Li Wei',
    founderTitle: 'CEO (ex-CATL)',
    traction: 'Tesla acquisition talks',
  },
  // 9. CENTRAL BANK COIN
  {
    id: 'vc_central_bank_coin',
    name: 'CENTRAL BANK COIN',
    tagline: 'Private CBDC infrastructure',
    category: 'fintech',
    tier: 'vc',
    raising: '$1B at $40B valuation',
    duration: [4, 6],
    outcomes: [
      { multiplier: 0, probability: 0.20, headline: 'CENTRAL BANK COIN HACKED - $1B STOLEN', marketEffects: { btc: 0.05, altcoins: 0.08 } },
      { multiplier: 0.5, probability: 0.20, headline: 'CENTRAL BANK COIN LOSES KEY CONTRACTS' },
      { multiplier: 1, probability: 0.20, headline: 'CENTRAL BANK COIN MODEST ADOPTION' },
      { multiplier: 3, probability: 0.25, headline: 'CENTRAL BANK COIN POWERS 20 COUNTRIES' },
      { multiplier: 5, probability: 0.10, headline: 'CENTRAL BANK COIN IPO - FINTECH GIANT', marketEffects: { btc: -0.03 } },
      { multiplier: 10, probability: 0.05, headline: 'CENTRAL BANK COIN BECOMES GLOBAL STANDARD', marketEffects: { btc: -0.08, altcoins: -0.10, dollar: 0.03 } },
    ],
    hints: {
      positive: ['CENTRAL BANK COIN SELECTED BY EU', 'CENTRAL BANK COIN 10 COUNTRIES IN PILOT'],
      negative: ['CENTRAL BANK COIN SECURITY FLAW FOUND', 'CENTRAL BANK COIN CHINA BANS PARTNERSHIP'],
    },
    hotTake: 'The rails for every government digital currency',
    pitch: "130 countries are exploring CBDCs but none can build the infrastructure. We provide the secure, scalable backbone. The EU selected us for their digital euro pilot. 10 more central banks are in talks.",
    founder: 'Christine Nakamoto',
    founderTitle: 'CEO (ex-IMF)',
    traction: 'EU digital euro selected',
  },
  // 10. INSTANT MORTGAGE
  {
    id: 'vc_instant_mortgage',
    name: 'INSTANT MORTGAGE',
    tagline: 'AI-powered 24-hour home loans',
    category: 'fintech',
    tier: 'vc',
    raising: '$500M at $20B valuation',
    duration: [4, 6],
    outcomes: [
      { multiplier: 0, probability: 0.20, headline: 'INSTANT MORTGAGE COLLAPSE - FRAUD SCANDAL', marketEffects: { reits: -0.03 } },
      { multiplier: 0.5, probability: 0.20, headline: 'INSTANT MORTGAGE DOWN ROUND' },
      { multiplier: 1, probability: 0.20, headline: 'INSTANT MORTGAGE SOLD TO BANK' },
      { multiplier: 3, probability: 0.25, headline: 'INSTANT MORTGAGE IPO SUCCESS' },
      { multiplier: 5, probability: 0.10, headline: 'INSTANT MORTGAGE DOMINATES MARKET', marketEffects: { reits: 0.03 } },
      { multiplier: 10, probability: 0.05, headline: 'INSTANT MORTGAGE ACQUIRED FOR $200B', marketEffects: { reits: 0.05, nasdaq: 0.02 } },
    ],
    hints: {
      positive: ['INSTANT MORTGAGE PROCESSES $10B IN LOANS', 'INSTANT MORTGAGE JPMORGAN PARTNERSHIP'],
      negative: ['INSTANT MORTGAGE AI APPROVES FRAUDULENT LOANS', 'INSTANT MORTGAGE HOUSING MARKET COOLING'],
    },
    hotTake: "Close on your house in 24 hours, not 45 days",
    pitch: "Mortgage approval takes 45 days because of manual document review. Our AI analyzes 1,000 data points and underwrites in minutes. We've processed $10B in loans with 0.1% default rate. JPMorgan wants to white-label our tech.",
    founder: 'David Park',
    founderTitle: 'CEO (ex-Rocket Mortgage)',
    traction: '$10B loans processed',
  },
  // 11. OCEAN MINING
  {
    id: 'vc_ocean_mining',
    name: 'OCEAN MINING',
    tagline: 'Deep sea mineral extraction',
    category: 'energy',
    tier: 'vc',
    raising: '$2B at $70B valuation',
    duration: [4, 6],
    outcomes: [
      { multiplier: 0, probability: 0.20, headline: 'OCEAN MINING ENVIRONMENTAL DISASTER - OPERATIONS HALTED', marketEffects: { lithium: 0.08, emerging: 0.05 } },
      { multiplier: 0.5, probability: 0.20, headline: 'OCEAN MINING UN MORATORIUM - YEARS OF DELAYS' },
      { multiplier: 1, probability: 0.20, headline: 'OCEAN MINING LIMITED PERMITS APPROVED' },
      { multiplier: 3, probability: 0.25, headline: 'OCEAN MINING IPO - RARE EARTH INDEPENDENCE', marketEffects: { lithium: -0.05 } },
      { multiplier: 5, probability: 0.10, headline: 'OCEAN MINING EXTRACTS $50B IN MINERALS', marketEffects: { lithium: -0.10, nasdaq: 0.02 } },
      { multiplier: 10, probability: 0.05, headline: "OCEAN MINING ENDS CHINA'S RARE EARTH MONOPOLY", marketEffects: { lithium: -0.15, nasdaq: 0.05, emerging: -0.08 } },
    ],
    hints: {
      positive: ['OCEAN MINING NODULE FIELD LARGER THAN EXPECTED', 'OCEAN MINING US NAVY CONTRACT FOR STRATEGIC MINERALS'],
      negative: ['OCEAN MINING GREENPEACE BLOCKADE', 'OCEAN MINING EQUIPMENT LOST AT 4000M DEPTH'],
    },
    hotTake: "End China's stranglehold on rare earths",
    pitch: "China controls 80% of rare earth minerals critical for EVs and defense. The Pacific seafloor has 10x more - just sitting there. Our autonomous collectors extract nodules at 4,000m depth. US Navy just signed a strategic contract.",
    founder: 'Admiral James Cole (ret.)',
    founderTitle: 'CEO (ex-Pacific Fleet)',
    traction: 'US Navy contract signed',
  },
  // 12. SHADOW BANK AI
  {
    id: 'vc_shadow_bank_ai',
    name: 'SHADOW BANK AI',
    tagline: 'AI-powered offshore finance',
    category: 'fintech',
    tier: 'vc',
    raising: '$1.5B at $50B valuation',
    duration: [4, 6],
    outcomes: [
      { multiplier: 0, probability: 0.20, headline: 'SHADOW BANK AI MONEY LAUNDERING SCANDAL - EXECS INDICTED', marketEffects: { btc: 0.05, altcoins: 0.08 } },
      { multiplier: 0.5, probability: 0.20, headline: 'SHADOW BANK AI REGULATORY CRACKDOWN - DOWN ROUND' },
      { multiplier: 1, probability: 0.20, headline: 'SHADOW BANK AI PIVOTS TO COMPLIANCE SOFTWARE' },
      { multiplier: 3, probability: 0.25, headline: 'SHADOW BANK AI IPO - WEALTH MANAGEMENT DISRUPTION' },
      { multiplier: 5, probability: 0.10, headline: 'SHADOW BANK AI MANAGES $500B FOR ULTRA-WEALTHY', marketEffects: { btc: -0.03 } },
      { multiplier: 10, probability: 0.05, headline: 'SHADOW BANK AI BECOMES OFFSHORE STANDARD', marketEffects: { btc: -0.05, gold: -0.03, nasdaq: 0.03 } },
    ],
    hints: {
      positive: ['SHADOW BANK AI SIGNS 50 BILLIONAIRE CLIENTS', 'SHADOW BANK AI WINS TAX COURT CASE - AI ADVICE VALID'],
      negative: ['SHADOW BANK AI LEAKED CLIENT LIST INCLUDES POLITICIANS', 'SHADOW BANK AI FLAGGED BY TREASURY DEPARTMENT'],
    },
    hotTake: 'Your offshore wealth manager never sleeps',
    pitch: "Ultra-high-net-worth individuals pay 2% annually for wealth management. Our AI handles multi-jurisdictional tax optimization, asset protection, and estate planning 24/7. 50 billionaire clients managing $500B with us.",
    founder: 'Marcus Sterling III',
    founderTitle: 'CEO (ex-Goldman Private)',
    traction: '50 billionaire clients',
  },
  // 13. MARS COLONY CORP
  {
    id: 'vc_mars_colony',
    name: 'MARS COLONY CORP',
    tagline: 'First permanent Mars settlement',
    category: 'space',
    tier: 'vc',
    raising: '$8B at $300B valuation',
    duration: [5, 6],
    outcomes: [
      { multiplier: 0, probability: 0.20, headline: 'MARS COLONY CORP ROCKET EXPLODES - PROGRAM CANCELLED', marketEffects: { nasdaq: -0.03, lithium: -0.05 } },
      { multiplier: 0.5, probability: 0.20, headline: 'MARS COLONY CORP DECADE OF DELAYS ANNOUNCED' },
      { multiplier: 1, probability: 0.20, headline: 'MARS COLONY CORP UNMANNED MISSION SUCCESS' },
      { multiplier: 3, probability: 0.25, headline: 'MARS COLONY CORP FIRST HUMANS LAND ON MARS', marketEffects: { nasdaq: 0.03, lithium: 0.05 } },
      { multiplier: 5, probability: 0.10, headline: 'MARS COLONY CORP ESTABLISHES PERMANENT BASE', marketEffects: { nasdaq: 0.05, lithium: 0.08, sp500: 0.02 } },
      { multiplier: 10, probability: 0.05, headline: 'MARS COLONY CORP FINDS WATER ICE - COLONIZATION VIABLE', marketEffects: { nasdaq: 0.08, lithium: 0.12, sp500: 0.03 } },
    ],
    hints: {
      positive: ['MARS COLONY CORP SUCCESSFUL CARGO LANDING', 'MARS COLONY CORP ELON, BEZOS BOTH INVEST'],
      negative: ['MARS COLONY CORP LIFE SUPPORT SYSTEM FAILS IN TESTING', 'MARS COLONY CORP KEY ENGINEER DEFECTS TO CHINA PROGRAM'],
    },
    hotTake: 'Humanity becomes a multi-planetary species',
    pitch: "This is the big one. We're not just visiting Mars - we're building humanity's first permanent off-world colony. Our habitat modules are tested, life support is proven, and the first crew is selected. Both Elon and Bezos invested because they know this changes everything.",
    founder: 'Dr. Mae Chen',
    founderTitle: 'CEO (ex-NASA Artemis)',
    traction: 'Elon + Bezos invested',
  },
]

export const ALL_STARTUPS = [...ANGEL_STARTUPS, ...VC_STARTUPS]
